spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false # https://kingbbode.tistory.com/27, https://gracelove91.tistory.com/100
    show-sql: false
    hibernate:
      ddl-auto: none # none | validate | update | create | create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    hikari:
      minimumIdle: 3
      maximumPoolSize: 10