server:
  port: 9010
  servlet:
    context-path: /customer

spring:
  application:
    name: petclinic-customer-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: petclinic-service-common, ${spring.application.name}
      fail-fast: true
      discovery:
        service-id: petclinic-config-server
        enabled: true