server:
  port: 80

spring:
  application:
    name: petclinic-api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      name: ${spring.application.name}
      fail-fast: true
      discovery:
        service-id: petclinic-config-server
        enabled: true
