spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./petclinic-visit

petclinic:
  kafka:
    producer:
      bootstrap-server: localhost:9091

resilience4j:
  circuitbreaker:
    instances:
      veterinarianCircuitBreaker:
        baseConfig: default
