server:
  port: 9020
  servlet:
    context-path: /veterinarian

spring:
  application:
    name: petclinic-veterinarian-service
  cloud:
    config:
      name: petclinic-service-common, ${spring.application.name}
      fail-fast: true
  config:
    import:
      - optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:tcp://localhost/./petclinic-veterinarian
