DROP TABLE VETERINARIAN_SPECIALTY IF EXISTS;
DROP TABLE VETERINARIAN IF EXISTS;
DROP TABLE SPECIALTY IF EXISTS;

CREATE TABLE VETERINARIAN (
  VETERINARIAN_ID INTEGER IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  CREATED_BY VARCHAR(36),
  CREATED_DATE TIMESTAMP,
  CREATED_IP VARCHAR(30),
  LAST_MODIFIED_BY VARCHAR(36),
  LAST_MODIFIED_DATE TIMESTAMP,
  LAST_MODIFIED_IP VARCHAR(30)
);
CREATE INDEX VETERINARIAN_LAST_NAME ON VETERINARIAN (LAST_NAME);

CREATE TABLE SPECIALTY (
  SPECIALTY_ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(80),
  CREATED_BY VARCHAR(36),
  CREATED_DATE TIMESTAMP,
  CREATED_IP VARCHAR(30),
  LAST_MODIFIED_BY VARCHAR(36),
  LAST_MODIFIED_DATE TIMESTAMP,
  LAST_MODIFIED_IP VARCHAR(30)
);
CREATE INDEX SPECIALTY_NAME ON SPECIALTY (NAME);

CREATE TABLE VETERINARIAN_SPECIALTY (
  VETERINARIAN_ID INTEGER NOT NULL,
  SPECIALTY_ID INTEGER NOT NULL,
  CREATED_BY VARCHAR(36),
  CREATED_DATE TIMESTAMP,
  CREATED_IP VARCHAR(30),
  LAST_MODIFIED_BY VARCHAR(36),
  LAST_MODIFIED_DATE TIMESTAMP,
  LAST_MODIFIED_IP VARCHAR(30)
);
ALTER TABLE VETERINARIAN_SPECIALTY ADD CONSTRAINT FK_VETERINARIAN_SPECIALTY_VETERINARIAN FOREIGN KEY (VETERINARIAN_ID) REFERENCES VETERINARIAN (VETERINARIAN_ID);
ALTER TABLE VETERINARIAN_SPECIALTY ADD CONSTRAINT FK_VETERINARIAN_SPECIALTY_SPECIALTY FOREIGN KEY (SPECIALTY_ID) REFERENCES SPECIALTY (SPECIALTY_ID);
