server:
  port: 8888

spring:
  application:
    name: petclinic-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/yongsang/Development/workspaces/java/petclinic-cloud/petclinic-cloud-config