server:
  port: 9030
  servlet:
    context-path: /visit

spring:
  application:
    name: petclinic-visit-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: petclinic-service-common, ${spring.application.name}
      fail-fast: true
      discovery:
        service-id: petclinic-config-server
        enabled: true

#logging:
#  level:
#    org.springframework.cloud.openfeign: debug
#    feign: debug
#    io.github.resilience4j: debug

# TODO config ecrypt 적용
# TODO spring security 및 api gateway 인증 처리??
#  - OAuth2
# TODO cache 는?
