server:
  port: 9030
  servlet:
    context-path: /visit

spring:
  application:
    name: petclinic-visit-service
  cloud:
    config:
      name: petclinic-service-common, ${spring.application.name}
      fail-fast: true
  config:
    import:
      - optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:tcp://localhost/./petclinic-visit
