server:
  port: 9030
  servlet:
    context-path: /visit

spring:
  application:
    name: petclinic-visit-service
  cloud:
    config:
      name: petclinic-service-common, ${spring.application.name}
      fail-fast: true
      # TODO 적용해보기..
#      discovery:
#        service-id: petclinic-config-server
#        enabled: true
  # 이 설정은 불필요한 거 아닌가??
  config:
    import:
      - optional:configserver:http://localhost:8888

#logging:
#  level:
#    io.github.resilience4j: debug
