server:
  port: 9030
  servlet:
    context-path: /visit

spring:
  application:
    name: petclinic-visit-service
  config:
    import: classpath:petclinic-common.yml # http://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html, https://www.baeldung.com/properties-with-spring
  datasource:
    url: jdbc:h2:tcp://localhost/~/Development/database/petclinic-visit
