INSERT INTO VISIT (VISIT_ID, PET_ID, VETERINARIAN_ID, VISIT_DATE, DESCRIPTION) VALUES (1, 7, 1, '2013-01-01', 'rabies shot');
INSERT INTO VISIT (VISIT_ID, PET_ID, VETERINARIAN_ID, VISIT_DATE, DESCRIPTION) VALUES (2, 8, 3, '2013-01-02', 'rabies shot');
INSERT INTO VISIT (VISIT_ID, PET_ID, VETERINARIAN_ID, VISIT_DATE, DESCRIPTION) VALUES (3, 8, 5, '2013-01-03', 'neutered');
INSERT INTO VISIT (VISIT_ID, PET_ID, VETERINARIAN_ID, VISIT_DATE, DESCRIPTION) VALUES (4, 7, 6, '2013-01-04', 'spayed');
